public with sharing class BaseConstants {
    public static final String API_ENDPOINT_CURRENT = 'https://oktana-e0-dev-ed.develop.my.site.com/tech/services/apexrest/WeatherService/current/';
    public static final String API_ENDPOINT_FORECAST = 'https://oktana-e0-dev-ed.develop.my.site.com/tech/services/apexrest/WeatherService/forecast/';
    public static final List<String> DEFAULT_LOCATIONS = new List<String>{'Asunción','Montevideo','La Paz','Quito','São Paulo', 'Madrid', 'New York','West Virginia','Paris','Roma','Tokio','Seoul'};
}